import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { getGlobal } from "@/data/loaders";
import { Footter } from "@/components/layout/Footer";

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  weight: ["200", "400", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  const { data } = await getGlobal();
  if (!data) throw new Error("Failed to fetch global setting");
  return { data };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await loader();

  return (
    <html lang="en">
      <body className={`${barlowCondensed.variable} antialiased font-main`}>
        <Header header={data.header} />
        {children}
        <Footter footer={data.footer} />
      </body>
    </html>
  );
}
